### ISSUE TITLE
[SEO] Non latest documentation should not be referenced by Search engines

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1960] opened 2024-10-08 11:08 UTC
### Issue Description

If you search `taipy table` on Google, the first result is a page from our docs but not the latest version: https://docs.taipy.io/en/release-3.0/knowledge_base/tips/using_tables/

We need to find a way to only have the latest documentation version referenced in search engines: https://docs.taipy.io/en/latest/tutorials/visuals/2_using_tables/

This must be solved within taipy-doc repository.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by SGCODEX** [comment] 2024-10-08 11:46
Sir, I am interested to work on it.

**Comment by Rishi-0007** [comment] 2024-10-08 11:46
Please assign this issue to me.

**Comment by rabelmervin** [comment] 2024-10-08 13:02
Hi sir @AlexandreSajus, I'm interested to work on this issue....

**Comment by RaedenCodes** [comment] 2024-10-08 13:25
Please assign it to me I would like to work on it @jrobinAV @AlexandreSajus

**Comment by rajasurya-rjs** [comment] 2024-10-09 05:52
good morning i have solved the issue could please check the pr and tell me if any other thing which i need to add in the them

**Comment by loadinglit** [comment] 2024-10-09 10:18
Hey I have checked the existing issue, I am willing to work on it. can you assign this issue to me. @AlexandreSajus

**Comment by FlorianJacta** [comment] 2024-10-09 11:50
I have assigned you all to this issue. We will look into your proposal as soon as we can @rajasurya-rjs

**Comment by rabelmervin** [comment] 2024-10-09 11:52
Hi @FlorianJacta I'm interested to solve this issue in collaboration with others... Could you please assign me

**Comment by FlorianJacta** [comment] 2024-10-09 12:05
Let's go @rabelmervin . The issue is to be fixed in [Taipy Doc](https://github.com/Avaiga/taipy-doc/)

**Comment by wizaye** [comment] 2024-10-09 17:15
hey @FlorianJacta  i see the pr is still open , would like to give my contribution to this issue, please assign this to me

**Comment by loadinglit** [comment] 2024-10-10 09:43
Hello @jrobinAV, @FlorianJacta,
I have submitted two pull requests to address issue **#1960** from the taipy repository to the taipy-doc repo.

1. **Pull Request 1**:  Updates the documentation in the taipy-doc repository that addresses issue 1960 from the taipy repository. The changes include the update to index.md in the release 3.0 branch to direct users to the latest documentation.  https://github.com/Avaiga/taipy-doc/pull/1158#issue-2578209084
 
2. **Pull Request 2**: Updated the `robots.txt` file in the `taipy-doc` repository. This PR updates the robots.txt file to improve SEO by allowing indexing of the latest documentation and version 4.0 while disallowing older versions to ensure latest documentation visibility 
https://github.com/Avaiga/taipy-doc/pull/1159#issue-2578307060 

These modifications are essential for maintaining clarity in documentation access and ensuring users find the most relevant information.

Please consider linking these pull requests to issue **#1960** for better tracking. Thank you for your attention!

**Comment by loadinglit** [comment] 2024-10-10 12:41
https://github.com/Avaiga/taipy-doc/pull/1160#issue-2578731657 

check this for issue #1960 
@jrobinAV @FlorianJacta

**Comment by sajithcode** [comment] 2024-10-15 17:15
Sir, I am interested to work on it.

**Comment by jrobinAV** [comment] 2024-10-16 07:39
@sajithcode You can always propose a new PR on that issue.

But we already have two PRs that are supposed to solve the issue. Before proposing your solution, maybe you can review the PRs https://github.com/Avaiga/taipy-doc/pull/1160 and https://github.com/Avaiga/taipy-doc/pull/1154 to see if you would do it differently.

**Comment by 000xs** [comment] 2024-10-18 03:45
@AlexandreSajus 
https://docs.taipy.io/en/latest/tutorials/visuals/2_using_tables/ This not found!

![image](https://github.com/user-attachments/assets/5a962bd7-1f17-4c02-88c0-b909f801a7bd)

**Comment by AlexandreSajus** [comment] 2024-10-18 09:59
My bad, maybe the link got changed, here is the current link: https://docs.taipy.io/en/latest/tutorials/articles/using_tables/

**Closed as completed** 2024-11-04 18:06 UTC
Labels: 📄 Documentation, 💥Malfunction, 🆘 Help wanted, 🟧 Priority: High, 🥶Waiting for contributor
