### ISSUE TITLE
Expand the `exposed_type` parameter of DataNode to accept actual Python types

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy#398] opened 2022-12-05 05:14 UTC
**Description**

For now, the `exposed_type` parameter only accepts a string (`"pandas", "numpy") or a custom python class.

This ticket proposes to expand the parameter type to accept actual Python types for the predefined types:
- `numpy.array`
- `pandas.DataFrame`

**Comment by sqrt676** [comment] 2024-03-01 18:52
Can i help out here ?

**Comment by trgiangdo** [comment] 2024-03-02 02:38
Thank you @sqrt676. I assigned the ticket to you.

Let us know if you need more information on this.

**Comment by sqrt676** [comment] 2024-03-02 18:10
Thanks @trgiangdo , will ask for information wherever needed.

**Comment by trgiangdo** [comment] 2024-03-22 06:10
Hello @sqrt676, any update on this issue?

**Comment by ranjanmangla1** [comment] 2024-07-11 06:23
@trgiangdo can I take this one?

**Comment by trgiangdo** [comment] 2024-07-11 06:28
Absolutely. I will assign the issue to you @ranjanmangla1.

If you have any question on the topic, feel free to ask here.

**Comment by ranjanmangla1** [comment] 2024-07-11 06:33
@trgiangdo just want to ask, since this issue is almost 18 months old now, what changes have been to taipy? and since modin has been deprecated in taipy, is there a need to provide support for modin.pandas.DataFrame?

**Comment by trgiangdo** [comment] 2024-07-11 06:41
Oh, you're right. Let me update the description. Other than that, there hasn't been any other change that affect this issue.

**Comment by NILAY1556** [comment] 2024-09-17 13:02
hi , @trgiangdo 
I'd like to contribute to this issue. Is it still open?

**Comment by jrobinAV** [comment] 2024-09-23 08:47
Hello @NILAY1556,

Yes, it is still open.

Let me assign it to you.

Thank you,

**Comment by SaiNivedh26** [comment] 2024-10-31 04:28
Hey can I take up this issue ?

**Comment by jrobinAV** [comment] 2024-10-31 15:18
@SaiNivedh26 That would be great. Thank you.

**Comment by sohamkumar05** [comment] 2024-11-21 05:27
@jrobinAV, please confirm whether this issue needs to be open. I already see a merged PR done based on the requirements mentioned in the issue. If yes, please elaborate on the requirement, because what is asked in the issue is already addressed.

Also, I would like to take this issue if requirements are yet to be fulfilled.

**Comment by jrobinAV** [comment] 2024-11-25 09:57
Hello @sohamkumar05,

Thank you for your help. Yes, indeed, this is still open to contribution. Let me assign it to you.

Let me give a fake example with a CSV data node. Today, the code should look like the following.
```python
import taipy as tp

cfg = tp.config.Config.configure_csv_data_node(
    id="my_id", scope: tp.Scope.GLOBAL, default_path="my/path.csv",
    exposed_type="pandas") # The `exposed_type` parameter is a string

dn = tp.create_global_datanode(cfg)
```

This issue is about accepting the following code:
```python
import taipy as tp
import pandas as pd

cfg = tp.config.Config.configure_csv_data_node(
    id="my_id", scope: tp.Scope.GLOBAL, default_path="my/path.csv",
    exposed_type=pd.DataFrame)  # The `exposed_type` can be a predefined DataFrame type

dn = tp.create_global_datanode(cfg)
```

**Closed as completed** 2024-12-24 02:38 UTC
Labels: Core, 📈 Improvement, 📄 Documentation, good first issue, 🟩 Priority: Low, Core: 📁 Data node
