### ISSUE TITLE
scenario_selector: rendering in dark mode

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#2074] opened 2024-10-16 16:59 UTC
### What went wrong? 🤔

This is a screenshot showing a scenario selector control in dark mode:
![image](https://github.com/user-attachments/assets/2820ea7d-6d6f-4440-892a-0814384dd7e4)

Note that one of the toolbar buttons is black, as are all the 'edit' buttons.

Also, the search button in the toolbar does not have a tooltip, contrary to his two neighbors. I'm just sayin'.

### Expected Behavior

All button icons should turn to a bright color.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by saumy-sh** [comment] 2024-10-16 19:44
Hey I would very much like to work on this issue. Can you assign it to me?

**Comment by aksbalaguru** [comment] 2024-10-16 19:47
Hey I would like to contribute my knowledge to help fix this issue. Could you please assign this issue to me?

**Comment by FredLL-Avaiga** [comment] 2024-10-16 19:55
With Stylekit changes ?
By default, it renders as 
![image](https://github.com/user-attachments/assets/137d4191-c21c-4536-88c2-bedaa01413c2)

**Comment by FabienLelaquais** [comment] 2024-10-17 06:07
@saumy-sh and @aksbalaguru 
Please hold on a little bit.

This issue was just created and has not been qualified whatsoever.
We will keep you posted.
Thanks

**Comment by saumy-sh** [comment] 2024-10-17 07:13
Okay sure!

**Comment by saumy-sh** [comment] 2024-10-18 19:45
Is there any update on it? Will we be assigned this issue?

**Comment by FredLL-Avaiga** [comment] 2024-10-18 20:10
> Is there any update on it? Will we be assigned this issue?

I don't think this issue is opened to contributors yet

**Comment by saumy-sh** [comment] 2024-10-18 20:12
So this issue isn't available under hacktoberfest for contribution right?

**Comment by FredLL-Avaiga** [comment] 2024-10-18 20:42
not now anyway

**Comment by jrobinAV** [comment] 2024-10-21 15:59
I was not able to reproduce the issue.

**Comment by jrobinAV** [comment] 2024-11-18 10:38
Not reproducible.

**Closed as not planned by jrobinAV** 2024-11-18 10:38 UTC
Labels: 💥Malfunction, 🟩 Priority: Low
