### ISSUE TITLE
"Understanding GUI" tutorial should use debug=True to show full error trace

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#512] opened 2023-11-30 17:03 UTC
When something goes wrong when calling a callback function, only the Exception text is returned:

```bash
on_action(): Exception raised in 'update_transactions()':
Length of values (2028) does not match length of index (100000)
on_action(): 'update_transactions' is not a valid function.
```

This makes things hard to debug as I don't know what series of calls led to this Exception as well as where in the code this happens.

Ideally, error reporting should work just as in Python by giving you which series of calls led to the Exception and on which lines and files of code they happened. Is this possible?

**Comment by FlorianJacta** [comment] 2023-12-01 08:22
You can see the full stacktrace in Taipy 3.0 (https://github.com/Avaiga/taipy-gui/issues/933) by adding `debug=True` to your *run* method:

```python
...
gui = Gui(...)
gui.run(debug=True)
```

How can we document `debug=True` ?

**Comment by AlexandreSajus** [comment] 2023-12-01 09:34
Maybe this should be the default? Why would I not want the full stack trace?

**Comment by FlorianJacta** [comment] 2023-12-01 15:52
@FredLL-Avaiga @FabienLelaquais

**Comment by FabienLelaquais** [comment] 2023-12-01 20:26
@FlorianJacta "How can we document debug=True?"
These are documented in the Configuration section for GUI, pointed to be the Reference Manual entry for Gui.run().
In this section, you can read: "If debug is set to True, exceptions in user code will show the stack trace in the application's console."

@AlexandreSajus 
No. We will not set the debug mode by default, which would have unexpected impacts on the overall performance (memory/speed).
Now the point is not to hide the stack, but to expose it when developing and debugging the application. Therefore debug=True.

**Comment by AlexandreSajus** [comment] 2023-12-04 02:09
Understood. A good way to document this would be to set `debug=True` in the "Understanding GUI" tutorial, as it is generally the first step in users' learning journey of Taipy front-end.

**Comment by FlorianJacta** [comment] 2023-12-04 10:22
This would be the way to go, I think!

**Comment by FlorianJacta** [comment] 2023-12-04 12:05
Duplicate of https://github.com/Avaiga/taipy/issues/524

**Closed as completed** 2023-12-04 13:36 UTC
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium
