### ISSUE TITLE
[🐛 BUG] data_node visual element shows error in the "properties" tab

### ISSUE THREAD

**Issue by enarroied** [Avaiga/taipy#2121] opened 2024-10-21 18:16 UTC
### What went wrong? 🤔

The data_node visual element shows an error message in the browser when I click on "properties".

The error occurs in the browser only; nothing is printed in the terminal. You can see the errors in the images below. This happens in three browsers (Brave, Chrome, Firefox); it's not a caching problem.

When I click on "Try Again", the front end shows my app again and keeps working. Otherwise, the data_node element works.

### Expected Behavior

I should see the the properties.

### Steps to Reproduce Issue

This code gives me the error:

```python
import taipy as tp
import taipy.gui.builder as tgb
from taipy import Config, Orchestrator, Scope
from taipy.gui import Gui

bug_node = Config.configure_data_node(
    id="bug_node",
    default_data="bug",
    scope=Scope.GLOBAL,
)

with tgb.Page() as data_node_viewer:
    tgb.text("## Discovering Data Node viewers", mode="md")

    tgb.data_node(
        data_node="{bug_data_node}",
    )
bug_gui = Gui(page=data_node_viewer)

if __name__ == "__main__":
    orchestrator = Orchestrator()
    orchestrator.run()
    bug_data_node = tp.create_global_data_node(bug_node)
    bug_gui.run(
        use_reloader=True,
    )
```

### Screenshots

This is how the error looks in Brave and Chrome:

![brave error message](https://cdn.discordapp.com/attachments/1125818635856920768/1296569110175420578/image.png?ex=6716b814&is=67156694&hm=96bd1f24912db2698691dd5fa24246f3ea9bba93b77ffc6192474574d7d992a1&)

This is how it looks in Firefox:

![firefoxerror message](https://cdn.discordapp.com/attachments/1125818635856920768/1296801151374589962/image.png?ex=6716e76f&is=671595ef&hm=512e1bb720b90b68e120f8852cff5af3781a671aed62ea47d4bdf6b491e3b732&)

### Runtime Environment

Windows 10, I used Python 12 within Anaconda, Taipy 4.0.0

### Browsers

Chrome, Firefox, Brave

### OS

Windows

### Version of Taipy

4.0.0

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment] 2024-10-21 19:44
Tested on Develop and ... works for me (tm)
We should make sure that this is fixed in the coming 4.0.1 @FlorianJacta

**Comment by TSP06** [comment] 2024-10-22 02:35
Hey @FredLL-Avaiga would like to take this up

**Comment by mithelan** [comment] 2024-10-22 04:07
Hi @FredLL-Avaiga Can i take it up

**Comment by FlorianJacta** [comment] 2024-10-22 07:11
I wasn't able to reproduce it too @FredLL-Avaiga but you might have some idea

**Comment by FredLL-Avaiga** [comment] 2024-10-22 07:41
@FlorianJacta did you try 4.0 or develop or the next technical release ?

**Comment by FredLL-Avaiga** [comment] 2024-10-22 07:41
> Hey @FredLL-Avaiga would like to take this up

Sorry this not opened to contribution ...yet

**Comment by FlorianJacta** [comment] 2024-10-22 07:48
I tested 4.0, Enterprise Develop (from a few days), and Enterprise 4.0

**Comment by enarroied** [comment] 2024-10-25 20:11
I just noticed that if I add:
```
show_properties=False,
```
The properties show and without the error...

![image](https://github.com/user-attachments/assets/c90f720a-2ee8-4909-975f-fa43a011fc53)

**Comment by FabienLelaquais** [comment] 2024-10-28 08:28
So first of all, there is a bad confusion in the Taipy control naming.
`show_properties` should apply to the TAB (just like `show_data` and `show_history`), which is does not at this point.
We will need to add a new Boolean `show_custom_properties` property (defaults to True) to specifically target those properties - what `show_properties` does as of today), and have `show_properties` control the visibility of the tab itself.

Second, we don't seem to be able to reproduce that problem at this point.
If there is no problem when rendering the page, and the problem disappears on reload, I suggest we implement what I propose and move on.

@enarroied what do you think?

**Comment by enarroied** [comment] 2024-10-29 07:04
Hi Fabien,
Thank you all for looking into this.
It's a bit strange that no one can reproduce it, but at some point, you have to move forward. 
However, while the page renders without error, the problem doesn't' disappear on reload: The properties TAB is never usable unless I add:  `show_properties=False`.

I put a gif with the issue I encounter, for reference, in case someone else sees it in the future:

![2121](https://github.com/user-attachments/assets/9efbe7d7-88f9-4760-80d2-963e85f5dbea)

And I think applying `show_properties` to the "properties" TAB is a good idea, to make it consistent with the other arguments in the function.

**Comment by FabienLelaquais** [comment] 2024-10-29 18:16
Here is what we are going to do, @enarroied.
This `show_properties` thing was a mistake from day 1. We are changing 4.0 so that this property now applies to the Properties tab visibility, for homogeneity. A new property called `show_custom_properties` will be made available to target the Custom Properties list in the Properties tab - if it is visible.

I tried all sorts of combinations to reproduce your error - and could not.
Please give a try to 4.0.1 when it's out (a matter of days) and let us know.

Do that sound good to you?

P.S.: When you get a textual error, please grab it and copy is as text in this issue: we can hardly read it in an animated gif that we cannot stop...

**Comment by enarroied** [comment] 2024-10-29 18:47
Hi Fabien,

For the record, this is the error message with Brave and Chrome:
Something went wrong ...
object null is not iterable (cannot read property Symbol(Symbol.iterator))

And this is the error message on Firefox:
Something went wrong ...
(destructured parameter) is null

**Comment by enarroied** [comment] 2024-10-29 18:55
Also, since this seems to be a problem that's hard to reproduce, I assumed it would be easy to not have it...
**I installed Taipy 4.0.0 in a different environment, and I don't have the error anymore.**

Here is what I think happened: I did a pip install -U taipy

When I do `pip list` inside my buggy environment, I have all the 4.0.0 versions (taipy, taipy-gui...) but there seems to be a rebel taipy-config 3.1.1 left. Could the problem come from there?

If I uninstall taipy-config, the app doesn't work anymore. If I uninstall taipy (all of it) and re-install it, it works fine again. This doesn't install any taipy-config file.

**Comment by FredLL-Avaiga** [comment] 2024-10-29 20:17
Thanks for the detective work @enarroied 
This taipy-config 3.1 staying back after an upgrade to 4.0 is annoying.
We should take a look at it.
What do you think @jrobinAV @FabienLelaquais

**Comment by FabienLelaquais** [comment] 2024-10-30 08:05
Oooh that's certainly due to the packages organizations changes that happened in 4.0...
I suspect (not that I know what to do for sure) that this will have to be installed manually. Not a good look.

**Comment by FredLL-Avaiga** [comment] 2024-10-30 08:31
you mean uninstall manually ?
Can we automate some cleaning in the 4.0 installation process ?

**Comment by jrobinAV** [comment] 2024-10-30 11:13
We probably have a workaround (we need to confirm that), which is to uninstall taipy-config before upgrading taipy, but still, we need to have a close look at it. I agree @FredLL-Avaiga.

**Comment by jrobinAV** [comment] 2024-10-31 13:54
> you mean uninstall manually ? Can we automate some cleaning in the 4.0 installation process ?

taipy-config is considered an external dependency in taipy 3.X versions. We cannot decide to uninstall an external dependency when installing, uninstalling, or upgrading taipy because the external dependency could be used by another package. Even if it is unlikely that it will happen, it's a question for the package management tool used and not for taipy.

I found some interesting answers and tools in this StackOverflow post :
https://stackoverflow.com/questions/7915998/does-uninstalling-a-package-with-pip-also-remove-the-dependent-packages
In particular, the [pip3-autoremove](https://pypi.org/project/pip3-autoremove/) tool.

**Comment by jrobinAV** [comment] 2024-11-04 11:04
A dedicated issue has been created for the taipy-config issue.

**Closed as completed by jrobinAV** 2024-11-04 11:04 UTC
Labels: Core, 🟥 Priority: Critical, 💥Malfunction, GUI: Front-End
