### ISSUE TITLE
Input lagging in Login control

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1440] opened 2024-06-21 08:54 UTC
### Description

The login control will lag when the application is deployed in some way. It will be difficult to write in the text inputs and make the login control unusable.

This seems to be related to https://github.com/Avaiga/taipy/issues/610

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment] 2024-07-02 16:06
Is there a server where we could deploy an example provided by @FlorianJacta ? 
@florian-vuillemot @FabienLelaquais ?

**Comment by AlexandreSajus** [comment] 2024-07-08 10:27
Can't reproduce in Taipy 3.1.1.

You can try triggering the bug here: https://login-bug.taipy.cloud/

```python
from taipy.gui import Gui

username = ""


def on_login(state, id, login_args):
    username, password = login_args["args"][:2]
    state.username = username


page = """
<|Welcome to Taipy!|login|>

<|{username}|text|>
"""

Gui(page).run()
```

**Comment by FabienLelaquais** [comment] 2024-07-08 22:57
To me that works fine! (1 A.M. Paris time - could be a reason with low traffic)

**Comment by FlorianJacta** [comment] 2024-07-10 07:45
Works fine for me too!

**Comment by FredLL-Avaiga** [comment] 2024-07-10 07:46
Should one close it then ?

**Closed as completed** 2024-07-10 07:47 UTC
Labels: 📈 Improvement, 🖰 GUI, 🆘 Help wanted, 🟧 Priority: High
