### ISSUE TITLE
User theme (light or dark mode) should be an accessible variable

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1492] opened 2024-07-08 13:33 UTC
### Description

A user on Discord requested this. The user's theme (light or dark mode) should be a callable variable within the code. This way, the dev could have different images displayed according to the current theme (a white background image in light mode and a black background image in dark mode)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by ranjanmangla1** [comment] 2024-07-11 06:29
would love to work on this @AlexandreSajus. can you assign me this issue?

**Comment by jrobinAV** [comment] 2024-07-11 17:59
@ranjanmangla1 The "Help wanted" and "good first issue" labels have been misused on this issue. The issue has not been validated nor discussed with the maintainer team, yet.

We will discuss it as soon as possible (probably tomorrow) and will let you know if the issue is ok to be assigned.

Thank you for your understanding.

**Comment by jrobinAV** [comment] 2024-07-12 13:20
A priori, it will be implemented as a CSS rule. The documentation should provide an example.

**Comment by sOnU1002** [comment] 2024-10-02 17:21
hey i would like to work on the issue

**Comment by PayalKumari10** [comment] 2024-10-02 18:46
Hello @jrobinAV ,

I would like to work on this issue and help implement the theme-based image display functionality. My plan is to:
- Ensure the user's theme (light or dark mode) is stored as a variable in the code.
- Implement conditional logic to switch between light and dark mode images.
- Write unit tests to achieve at least 90% code coverage.
- Document the changes in taipy-doc and consider updating or creating a demo based on this.

Could you please assign this issue to me? Thank you!

**Comment by sangram-mkj-01** [comment] 2024-10-03 06:13
hey, I would like to work on this issue. You can assign this to me.
Thanks

**Comment by FlorianJacta** [comment] 2024-10-03 07:18
I will assign @sOnU1002 as it was the first reply. Thank you for your contribution!

@PayalKumari10, @sangram-mkj-01, there are a lot of issues to take!

**Comment by sOnU1002** [comment] 2024-10-03 07:31
can u please specify wherei have add the code

**Comment by FlorianJacta** [comment] 2024-10-03 07:51
@FabienLelaquais will know which people in R&D you should talk to

**Comment by sanketshinde3001** [comment] 2024-11-08 09:46
@FlorianJacta Should i work on it

**Closed as completed** 2024-12-23 08:10 UTC
Labels: 🖰 GUI, 🆘 Help wanted, 🟩 Priority: Low, ✨New feature
