### ISSUE TITLE
partial.update_content() not updating as expected

### ISSUE THREAD

**Issue by chrisOnWheels** [Avaiga/taipy#562] opened 2023-08-16 06:34 UTC
**Description**
I expected partial.update_content() to immediately change a partial, which would allow for a dynamic element. In a callback there is immediate reaction to changes in the bound variables, but partial.update_content() seems to execute after the callback has finished. This leads to a raised exception in the example. 

**How to reproduce**
```python
import taipy as tp


def make_partial(state):
    state.my_partial.update_content(state, """<|empty|>""")

    if state.select == "with Y":
        state.data_for_display = state.data
    else:
        state.data_for_display = state.data2

    content = """<|
"""
    for key in state.data_for_display.keys():
        content = (
            content + key + """ = <|{data_for_display['""" + key + """']}|><br />"""
        )
    content = (
        content
        + """
|>"""
    )

    state.my_partial.update_content(state, content)


if __name__ == "__main__":
    data = {"x": "X", "y": "Y"}
    data2 = {"x": "X"}

    data_for_display = data
    select = 1

    gui = tp.Gui()
    gui.add_page(
        "page",
        page="""
<|selector|value={select}|lov={['with Y','Exception without Y']}|adapter={lambda i: str(i)}|on_change=make_partial|>
<br />
<|part|partial={my_partial}|>  
""",
    )

    my_partial = gui.add_partial(page="""""")

    tp.run(gui)
```

**Comment by FredLL-Avaiga** [comment] 2023-09-14 17:09
partial update is asynchronous by design

**Comment by FredLL-Avaiga** [comment] 2023-09-14 17:26
you could add a bit of test in your expression to avoid the exception

```python
from taipy.gui import Gui


def make_partial(state):
    state.my_partial.update_content(state, "<|empty|>")

    if state.select == "with Y":
        state.data_for_display = state.data
    else:
        state.data_for_display = state.data2

    content = """<|
"""
    for key in state.data_for_display.keys():
        content = f"{content}{key} = <|{{data_for_display['{key}'] if '{key}' in data_for_display else ''}}|><br />"
    content += """
|>"""

    state.my_partial.update_content(state, content)


if __name__ == "__main__":
    data = {"x": "X", "y": "Y"}
    data2 = {"x": "X"}

    data_for_display = data
    select = None

    gui = Gui()
    gui.add_page(
        "page",
        page="""
<|selector|value={select}|lov=with Y;Exception without Y|on_change=make_partial|>
<br />
<|part|partial={my_partial}|>
""",
    )

    my_partial = gui.add_partial(page="")

    gui.run()

```

**Comment by FredLL-Avaiga** [comment] 2023-09-15 15:10
Does that answer your question @chrisOnWheels ?

**Comment by chrisOnWheels** [comment] 2023-09-19 07:29
Hi Fred,
 
this is exactly what I'm doing. Change the underlying data first, then rebuild/adapt the content for the partial, finally call update_partial. But I keep getting these exceptions.
My only problem is that these exceptions spam the console.
 
Best regards,
Chris

**Comment by FredLL-Avaiga** [comment] 2023-09-19 07:47
I don't get any exception with the code I provided.
Can you give me some example ?

**Comment by chrisOnWheels** [comment] 2023-09-19 10:12
I will try to isolate it, it's gonna take a while

**Comment by FredLL-Avaiga** [comment] 2023-09-19 10:14
👍

**Comment by FredLL-Avaiga** [comment] 2024-02-28 09:06
Hi @chrisOnWheels 
Is this issue still relevant ?

**Comment by chrisOnWheels** [comment] 2024-02-29 08:45
I'll not be working on the project in the near future, so it's up to you.
Thanks for the support :-)

**Comment by FabienLelaquais** [comment] 2024-03-08 14:23
Here is a modified version of the code that works properly.

All I did was postpone the update of state.data_for_display until just before the partial gets updated.
Please let us know if this works for you, so we can Close the issue with a smile on our faces.

```python
import taipy as tp


def make_partial(state):
    state.my_partial.update_content(state, "<|empty|>")

    new_data = data if state.select == "with Y" else data2
    content = "<|\n"
    for key in new_data.keys():
        content = content + key + f" = <|{{data_for_display['{key}']}}|><br />\n"
    content = content + "|>"

    state.data_for_display = new_data
    state.my_partial.update_content(state, content)


data = {"x": "X", "y": "Y"}
data2 = {"x": "X"}

if __name__ == "__main__":

    data_for_display = data
    select = 1

    gui = tp.Gui()
    gui.add_page(
        "page",
        page="""
<|selector|value={select}|lov={['with Y','Exception without Y']}|adapter={lambda i: str(i)}|on_change=make_partial|>
<br />
<|part|partial={my_partial}|>  
""",
    )

    my_partial = gui.add_partial(page="<|empty|>")

    tp.run(gui)
```

**Comment by jrobinAV** [comment] 2024-03-22 13:53
Closed as answered.

**Closed as completed by jrobinAV** 2024-03-22 13:53 UTC
Labels: 💥Malfunction, 🟧 Priority: High, Gui: Back-End
