### ISSUE TITLE
BUG-Scenario Visual Element, need to refresh webpage to make scenario submittable

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1076] opened 2024-04-02 09:07 UTC
Here's an example:
1. I have a scenario visual element that tells me the scenario cannot be submitted which is normal since the input data is not set
2. I set the input data by setting alpha to 2
3. The scenario visual element still tells me that I can't submit which is not normal
4. After a refresh of the page, I can submit the scenario
![core_issues_1_3](https://github.com/Avaiga/taipy/assets/62465003/92463a5a-1f67-4cba-b06c-a5b552b2a123)

The code is available here:
https://github.com/Avaiga/demo-mlp-regularization

**Comment by jrobinAV** [comment] 2024-04-02 16:16
This [issue](https://github.com/Avaiga/taipy/issues/746) should provide a solution to it. @FredLL-Avaiga @toan-quach Am I correct?

**Comment by FredLL-Avaiga** [comment] 2024-04-02 16:52
> This [issue](https://github.com/Avaiga/taipy/issues/746) should provide a solution to it. @FredLL-Avaiga @toan-quach Am I correct?

If the scenario is updated when its submittable state changes (and an event is emitted), yes

**Comment by jrobinAV** [comment] 2024-04-02 17:45
> > This [issue](https://github.com/Avaiga/taipy/issues/746) should provide a solution to it. @FredLL-Avaiga @toan-quach Am I correct?
> 
> If the scenario is updated when its submittable state changes (and an event is emitted), yes

Indeed, the objective is to emit an appropriate event. Thanks!

**Comment by jrobinAV** [comment] 2024-04-19 12:56
This is a duplicate of ticket #746.

**Closed as not planned by jrobinAV** 2024-04-19 12:56 UTC
Labels: Core, 🖰 GUI, 💥Malfunction, 🟧 Priority: High
