### ISSUE TITLE
BUG- Layout problem using Markdown file (.md) 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1255] opened 2024-05-02 12:28 UTC
**Description**
This issue seems to come from this issue: https://github.com/Avaiga/taipy/issues/458

Layout and parts need to be fixed.

**How to reproduce**

My Markdown
```
<|layout|columns=1 1 1|
<|
# Col 1
|>

<|
# Col 2
|>

<|
# Col 3
|>
|>
```

The result:
![image](https://github.com/Avaiga/taipy/assets/98709993/62f79b60-e440-4b8c-9f26-61b7f134a9e5)

**Expected behavior**
I should have parts and layout working properly.

**Runtime environment**
Please specify relevant indications.
 - Taipy: develop  commit: [84d5707](https://github.com/Avaiga/taipy/commit/84d5707f1a5c7545c869f7aedd0ff33517daed2a)

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by dinhlongviolin1** [comment] 2024-05-17 06:25
The issue is caused by file format that is in CRLF. The fix for this would be to replace all \r\n and \r with \n

**Closed as completed** 2024-05-17 07:47 UTC
Labels: 🟥 Priority: Critical, 🖰 GUI, 💥Malfunction, 🆘 Help wanted
