### ISSUE TITLE
[🐛 BUG] login control has frustrating input delay when deployed

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1478] opened 2024-07-04 13:05 UTC
### What went wrong? 🤔

Very similar to #610

The login control works fine locally, but when deployed, it has an input delay, which means the user will be typing characters, and some characters will disappear or appear later. I think this is exactly the issue we had with the input control in #610 

Could we add a property to login similar to change_delay for the input control where if change_delay=-1, Taipy will not refresh the username and password variables until the "Log In" button is pressed.

### Steps to Reproduce Issue

1. A code fragment
2. And/or configuration files or code
3. And/or Taipy GUI Markdown or HTML files

### Screenshots

![DESCRIPTION](LINK.png)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [ ] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment] 2024-07-05 15:15
This looks like a duplicate of #1440.
Can you help us replicate that issue and close this one?

**Closed as completed** 2024-07-08 09:42 UTC
Labels: 🖰 GUI, 💥Malfunction, 🟨 Priority: Medium
